apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-webapi
  namespace: healthmed
  labels:
    app: user-webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-webapi
  template:
    metadata:
      labels:
        app: user-webapi
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: user-webapi
        image: user-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
        env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_HOST
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: RABBITMQ_PASSWORD
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: ASPNETCORE_ENVIRONMENT
          - name: SQL_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: USER_CONNECTION_STRING