apiVersion: v1
kind: Service
metadata:
  name: user-webapi-service
  namespace: healthmed
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: user-webapi
  ports:
    - name: metrics
      port: 81
      targetPort: 8081
