apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-webapi
  namespace: healthmed
  labels:
    app: auth-webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-webapi
  template:
    metadata:
      labels:
        app: auth-webapi
    spec:
      initContainers:
        # - name: wait-for-postgres
          # image: busybox
          # command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
        
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: auth-webapi
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
        env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_HOST
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: RABBITMQ_PASSWORD
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: ASPNETCORE_ENVIRONMENT
          - name: POSTGRES_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: CONNECTION_STRING