apiVersion: v1
kind: Service
metadata:
  name: auth-webapi-service
  namespace: healthmed
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: auth-webapi
  ports:
    - name: metrics
      port: 82
      targetPort: 8082
