apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-webapi
  namespace: healthmed
  labels:
    app: appointment-webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointment-webapi
  template:
    metadata:
      labels:
        app: appointment-webapi
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: appointment-webapi
        image: appointment-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8083
        env:
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_HOST
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: RABBITMQ_PASSWORD
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: webapi-config
                key: ASPNETCORE_ENVIRONMENT
          - name: SQL_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: services-secret
                key: APPOINTMENT_CONNECTION_STRING