apiVersion: v1
kind: Service
metadata:
  name: calendar-webapi-service
  namespace: healthmed
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: calendar-webapi
  ports:
    - name: metrics
      port: 84
      targetPort: 8084
