name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: brsturner
  IMAGE_TAG: latest

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Calendar Service
        run: |
          docker build -t $REGISTRY/calendar-service:$IMAGE_TAG -f src/CalendarService/Med.Calendar.WebAPI/Dockerfile .
          docker push $REGISTRY/calendar-service:$IMAGE_TAG

      - name: Build and Push Appointment Service
        run: |
          docker build -t $REGISTRY/appointment-service:$IMAGE_TAG -f src/AppointmentService/Med.Appointment.WebAPI/Dockerfile .
          docker push $REGISTRY/appointment-service:$IMAGE_TAG

      - name: Build and Push Auth Service
        run: |
          docker build -t $REGISTRY/auth-service:$IMAGE_TAG -f src/AuthenticationService/Med.Authentication.WebAPI/Dockerfile .
          docker push $REGISTRY/auth-service:$IMAGE_TAG

      - name: Build and Push User Service
        run: |
          docker build -t $REGISTRY/user-service:$IMAGE_TAG -f src/UserService/Med.User.WebAPI/Dockerfile .
          docker push $REGISTRY/user-service:$IMAGE_TAG